### ISSUE TITLE
Error No connection

### ISSUE THREAD

**Issue by dindin56** [se-bastiaan/PopcornTimeRemote-Android#103]
Hay, 
       When ever I try and connect my Motorola G to PT I get an error saying 'No connection'. Which I don't understand, I have the latest version of popcorntime running on both devices, (Moto G and my PC (Windows 7). I have also installed the latest version on PT remote on my moto G.

Any advice on how to fix this?

-Dylan

**Comment by se-bastiaan** [comment]
Are you sure the ip address is correct?

**Comment by dindin56** [comment]
Yep, I typed it in at first, then used the QR code

**Comment by se-bastiaan** [comment]
Where did you get it? From Popcorn Time itself? It's not really reliable.

**Comment by dindin56** [comment]
![uxhucv6](https://cloud.githubusercontent.com/assets/11705141/6885626/b8f19e84-d620-11e4-85da-6e985c20112e.png)
![screenshot_2015-03-29-14-35-28 1](https://cloud.githubusercontent.com/assets/11705141/6885637/2aebf5ac-d621-11e4-9cae-74c9674a9f77.png)

**Comment by dindin56** [comment]
I'm running lollipop 5.0.2 if that changes anything

**Comment by se-bastiaan** [comment]
Can you try to visit http://localhost:8008 on your computer and send me the output.

**Comment by dindin56** [comment]
When i do that it says 'problem loading page'

Unable to connect

Firefox can't establish a connection to the server at localhost:8008.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by se-bastiaan** [comment]
And Popcorn Time is running when you do that?

**Comment by dindin56** [comment]
I didn't know it had to be running. 
I got:
       {"jsonrpc":"2.0","error":{"code":-32602,"message":"Unauthorized"},"id":null}

**Comment by se-bastiaan** [comment]
And what happens if you open http://192.168.56.1:8008/ on your phone in Chrome?

**Comment by dindin56** [comment]
Nothing, it just keeps loading and loading, but after a few minutes it says 'This web page is not available'

**Comment by se-bastiaan** [comment]
Then the ip address is not correct or your router is blocking connections.

What is the ip address of your phone?

**Comment by dindin56** [comment]
IP:
   PC:
         192.168.11.17
Phone:
           192.168.11.26

**Comment by se-bastiaan** [comment]
Then use 192.168.11.17 in the app

**Comment by dindin56** [comment]
thanks, it works now, just had the wrong IP in the Remote app.

-Dylan
