### ISSUE TITLE
no connection

### ISSUE THREAD

**Issue by tychotje** [se-bastiaan/PopcornTimeRemote-Android#108]
it indicates that there is no connection

**Comment by se-bastiaan** [comment]
Ok. How do you want me to fix this?

**Comment by tychotje** [comment]
I don't know. I checked the ip's, but they matched so now I don't know know what's the matter.

**Comment by se-bastiaan** [comment]
And where did you get the ip?

**Comment by tychotje** [comment]
at cdm on my pc. It was the same ip on popcorn time

**Comment by se-bastiaan** [comment]
Open your command line and execute `ifconfig`

**Comment by tychotje** [comment]
and after that

**Comment by se-bastiaan** [comment]
Enter the ip?

lmgtfy.com/?q=get%20local%20ip%20address

**Comment by tychotje** [comment]
it still says no connection

**Comment by se-bastiaan** [comment]
Then I can't help. Something is blocking your connection.
