### ISSUE TITLE
Subtitle menu load infinitely 

### ISSUE THREAD

**Issue by MaicolBen** [se-bastiaan/PopcornTimeRemote-Android#109]
Great App!

After touch the subtitles menu, the app try to load the subtitles and they never came(I waited 3 minutes with a good Internet connection).

Version 0.2.3.2. Android 4.3

Thanks

**Comment by PerfectSlayer** [comment]
Same here !
Version 0.2.3.2. Android 5.1.1

**Comment by MaicolBen** [comment]
I think that only happens on Series tab, seems to me that it is when the 'program' doesn't have the subtitles before play it.
