### ISSUE TITLE
App stuck at loading data when streaming to chromecast

### ISSUE THREAD

**Issue by Reflexzs** [se-bastiaan/PopcornTimeRemote-Android#34]
When streaming to chromecast, the app gets stuck on Popcorn Time is loading data...

![popcorn time](https://cloud.githubusercontent.com/assets/9627196/4964763/af599958-676c-11e4-82b3-910047810b9c.png)
![screenshot_2014-11-08-17-17-29](https://cloud.githubusercontent.com/assets/9627196/4964764/af6b621e-676c-11e4-9cf5-ec45ac2f4783.png)

**Comment by PerfectSlayer** [comment]
It's too bad the remote doesn't work when casting.
This app could be really useful in this case! :+1:

**Comment by se-bastiaan** [comment]
Yep. I know. But don't forget that Popcorn Time for Android has casting support.
