### ISSUE TITLE
App has disappeared from Google Play

### ISSUE THREAD

**Issue by Roboe** [se-bastiaan/PopcornTimeRemote-Android#83]
The app can not be found in [Google Play](https://play.google.com/store/apps/details?id=eu.se_bastiaan.popcorntimeremote) and there is no alternative download/update link.

Using GitHub [releases](https://github.com/se-bastiaan/PopcornTimeRemote-Android/releases) might be a workaround.

**Comment by se-bastiaan** [comment]
The app is available again. I added an in-app notice.

**Comment by Roboe** [comment]
Great! ;)
