### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joao7yt** [se-bastiaan/PopcornTimeRemote-Android#88]
When I click to open the instance that just added I get the message: "The Popcorn Time Remote application(eu.se_bastiaan.popcorntimeremote process) has stopped unexpectedly Try again." with the click options "Force finalization" and "Report". Se_bastiaan, can you help me? Thanks.

**Comment by se-bastiaan** [comment]
Device/Android version?

**Comment by joao7yt** [comment]
Yes

**Comment by joao7yt** [comment]
Wait, I understood that you were asking if I was using the version for android. But I think you asked what the version, right?
It's 2.3.4
